{{range  $index, $j := $.Values.clusterroles}}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusterrolebinding-{{ $index }}
subjects:
- kind: User
  name: {{ $j.nombre }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: {{ $j.permiso }}
  apiGroup: rbac.authorization.k8s.io
{{end}}